[features]
seeds = false
skip-lint = false

[programs.mainnet]
poi = "422WLuzcNAwXdG7YC4QFxhBYz7AcA4H6uCX2mo6UG8hp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
